version: "3.2"
services:
  python-app:
    container_name: 'python-app'
    build: .
    ports:
        - 5000:5000
    networks:
        - devops_test

  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    ports:
        - 9090:9090
    volumes:
        - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
        - python-app
    networks:
        - devops_test
        
        
  grafana:
    image: grafana/grafana
    container_name: 'grafana'
    ports:
        - 3000:3000
    depends_on:
        - python-app
    networks:
        - devops_test


networks:
  devops_test:
    driver: bridge
